#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.store.com:
    container_name: orderer.store.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/store.com/orderers/orderer.store.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/store.com/orderers/orderer.store.com/tls/:/var/hyperledger/orderer/tls
    - orderer.store.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.heatingplantorg.sensor.com:
    container_name: peer0.heatingplantorg.sensor.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.heatingplantorg.sensor.com
      - CORE_PEER_ADDRESS=peer0.heatingplantorg.sensor.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.heatingplantorg.sensor.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.heatingplantorg.sensor.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.heatingplantorg.sensor.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/heatingplantorg.sensor.com/peers/peer0.heatingplantorg.sensor.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/heatingplantorg.sensor.com/peers/peer0.heatingplantorg.sensor.com/tls:/etc/hyperledger/fabric/tls
        - peer0.heatingplantorg.sensor.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.housingcooperativeorg.sensor.com:
    container_name: peer0.housingcooperativeorg.sensor.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.housingcooperativeorg.sensor.com
      - CORE_PEER_ADDRESS=peer0.housingcooperativeorg.sensor.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.housingcooperativeorg.sensor.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.housingcooperativeorg.sensor.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.housingcooperativeorg.sensor.com:8051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
    volumes:
        - $UNIX_SOCK:/host/var/run/docker.sock
        - ../crypto-config/peerOrganizations/housingcooperativeorg.sensor.com/peers/peer0.housingcooperativeorg.sensor.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/housingcooperativeorg.sensor.com/peers/peer0.housingcooperativeorg.sensor.com/tls:/etc/hyperledger/fabric/tls
        - peer0.housingcooperativeorg.sensor.com:/var/hyperledger/production
    ports:
      - 8051:8051

  