#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.sensor.com:
  peer0.housingcooperativeorg.sensor.com:
  peer0.heatingplantorg.sensor.com:
  ca.housingcooperativeorg.sensor.com:
  ca.heatingplantorg.sensor.com:


networks:
  trade:
services:
  housing-ca:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporterorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.housingcooperativeorg.sensor.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.housingcooperativeorg.sensor.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/exporterorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.housingcooperativeorg.sensor.com:/etc/hyperledger/fabric-ca-server
    container_name: ca.housingcooperativeorg.sensor.com
    networks:
      - trade

  heating-ca:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    platform: $PLATFORM
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-importerorg
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.heatingplantorg.sensor.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --port 8054 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.heatingplantorg.sensor.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/importerorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.heatingplantorg.sensor.com:/etc/hyperledger/fabric-ca-server
    container_name: ca.heatingplantorg.sensor.com
    networks:
      - trade

  orderer.sensor.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.sensor.com
    container_name: orderer.sensor.com
    networks:
      - trade

  peer0.housingcooperativeorg.sensor.com:
    container_name: peer0.housingcooperativeorg.sensor.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.housingcooperativeorg.sensor.com
    networks:
      - trade

  peer0.heatingplantorg.sensor.com:
    container_name: peer0.heatingplantorg.sensor.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.heatingplantorg.sensor.com
    networks:
      - trade

